name: Main Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_account:
        description: 'AWS Account to deploy to (develop, stage, prod)'
        required: true
        default: 'develop'
      branch:
        description: 'Branch to build and deploy'
        required: true
        default: 'main'

permissions:
  id-token: write       # necessário para OIDC
  contents: read        # necessário para puxar o código do repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.aws_account || 'main' }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Definir role-to-assume
        run: |
          case "${{ github.event.inputs.aws_account }}" in
            prod)
              echo "role=${{ secrets.AWS_ROLE_ARN_PROD }}" >> $GITHUB_ENV
              ;;
            stage)
              echo "role=${{ secrets.AWS_ROLE_ARN_STAGE }}" >> $GITHUB_ENV
              ;;
            develop)
              echo "role=${{ secrets.AWS_ROLE_ARN_DEVELOP }}" >> $GITHUB_ENV
              ;;
            "" | main)
              echo "role=${{ secrets.AWS_ROLE_TO_ASSUME }}" >> $GITHUB_ENV
              ;;
            *)
              echo "❌ Invalid aws_account: ${{ github.event.inputs.aws_account }}"
              exit 1
              ;;
          esac

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.role }}
          aws-region: us-east-1

      - name: Deploy para S3 com AWS CLI
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete
        env:
          AWS_REGION: us-east-1

      - name: Invalidar cache CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: us-east-1
